spring:
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
  sql:
    init:
      mode: always
      schema-locations: classpath:sql/schema.sql

  rabbitmq:
    host: ${RABBIT_HOST}
    port: ${RABBIT_PORT}
    listener:
      simple:
        prefetch: 1

  quartz:
    job-store-type: jdbc
    jdbc:
      initialize-schema: always
    properties:
      org:
        quartz:
          quartzDataSource:
            URL:  jdbc:postgresql://${POSTGRES_QUARTZ_HOST}:${POSTGRES_QUARTZ_PORT}/${POSTGRES_QUARTZ_DB}
            driver: org.postgresql.Driver
            user: ${POSTGRES_QUARTZ_USER}
            password: ${POSTGRES_QUARTZ_PASSWORD}
          scheduler:
            instanceId: AUTO #?????????? AUTO, ??? ????, ????? ?????? ????? ??????? Scheduler`a ???? ?????????? ????????.
          jobStore:
            driverDelegateClass: org.quartz.impl.jdbcjobstore.PostgreSQLDelegate #????????? ??????? ??? ???????? ? ??
            useProperties: false #?????????, ??? ??? ?????? ? ?? ????? ????????? ? ???????? ?????, ? ?? ? ???????? ???????
            tablePrefix: QRTZ_  #??????? ?????? ? ??
            clusterCheckinInterval: 5000 #????????? ??????? ?????? ???????? Scheduler ? ?????????? ?????????? ? ????????
            isClustered: true #???????? ????? ?????? ? ????????
          threadPool: #????????? ????????? ??? ???????? ???? ?????, ?? ??????? ????? ??????????? ?????
            class: org.quartz.simpl.SimpleThreadPool
            threadCount: 10
            threadsInheritContextClassLoaderOfInitializingThread: true
    auto-startup: false #????????? ?????????????? ????? ??? scheduler, ?.?. ?????? ????? ???????? ???????


rabbit:
  mail-server:
    exchange-name: ${RABBIT_MAIL_SERVER_EXCHANGE_NAME}

    send-vacancy-response:
      queue-name: ${RABBIT_MAIL_SERVER_SEND_VACANCY_RESPONSE_QUEUE_NAME}
      routing-key: ${RABBIT_MAIL_SERVER_SEND_VACANCY_RESPONSE_ROUTING_KEY}

    send-payment-order:
      queue-name: ${RABBIT_MAIL_SERVER_SEND_PAYMENT_ORDER_QUEUE_NAME}
      routing-key: ${RABBIT_MAIL_SERVER_SEND_PAYMENT_ORDER_ROUTING_KEY}

    send-info-about-success-payment:
      queue-name: ${RABBIT_MAIL_SERVER_SEND_INFO_ABOUT_SUCCESS_PAYMENT_QUEUE_NAME}
      routing-key: ${RABBIT_MAIL_SERVER_SEND_INFO_ABOUT_SUCCESS_PAYMENT_ROUTING_KEY}


company-payment-info:
  inn: 1234567890
  kpp: 123456789
  company-name: 'ООО СУПЕРДЖОБ'
  company-account-number: 12345678901234567890
  bank-bik: 123456789
  bank-account-number: 12345678901234567890
  bank-name: 'ООО ТИНЬКОФФ БАНК'
  purpose-of-payment: 'За указание услуг по найму сотрудников'
  sum: 1000

page-size:
  vacancy: 30
  vacancy-response: 30
  payment-order: 30


scheduler:
  permanent-jobs-group-name: PERMANENT
  send-payment-order-job-cron: ${SEND_PAYMENT_ORDER_JOB_CRON}

quartz:
  send-payment-order:
    job-name: send-payment-order-job
    trigger-name: send-payment-order-trigger

management:
  endpoints:
    web:
      exposure:
        include: health,prometheus
  metrics:
    export:
      prometheus:
        enabled: true
    distribution:
      percentiles-histogram:
        "[http.server.requests]": true

server:
  port: 8080